version: '3.4'

services:
  lit.webapi:
    image: ${DOCKER_REGISTRY-}litwebapi
    container_name: BackEnd 
    build:
      context: .
      dockerfile: Back-End/LIT.WebAPI/Dockerfile
    depends_on: 
      - mongodb
    environment:
      MongoDBSettings__ConnectionString: "mongodb://admin:admin@mongodb:27017"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "3000:80"

  mongodb:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
      
  frontend:
    container_name: FrontEnd
    build:
      context: ./Fron-End/lit-web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - lit.webapi

volumes:
  mongodb_data:
