version: '3.4'

services:
  lit.webapi:
    image: ${DOCKER_REGISTRY-}litwebapi
    build:
      context: .
      dockerfile: LIT.WebAPI/Dockerfile
    depends_on: 
      - mongodb
    environment:
      DatabaseSettings__ConnectionString: "mongodb://admin:admin@mongodb:27017"

  mongodb:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: